// @ts-nocheck
import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import treksRouter from "./treks.js";
import joinRequestsRouter from "./joinRequests.js";
import customRequestsRouter from "./customRequests.js";
import bidsRouter from "./bids.js";
import bookingsRouter from "./bookings.js";
import dashboardRouter from "./dashboard.js";
import notificationsRouter from "./notifications.js";
import threadsRouter from "./threads.js";
import dmRouter from "./dm.js";
import weatherRouter from "./weather.js";
import permitsRouter from "./permits.js";
import emergencyContactsRouter from "./emergencyContacts.js";
import gearRouter from "./gear.js";
import seasonsRouter from "./seasons.js";
import teahousesRouter from "./teahouses.js";
import reviewsRouter from "./reviews.js";
import verificationRouter from "./verification.js";
import sosRouter from "./sos.js";
import adminRouter from "./admin.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(treksRouter);
router.use(joinRequestsRouter);
router.use(customRequestsRouter);
router.use(bidsRouter);
router.use(bookingsRouter);
router.use(dashboardRouter);
router.use(notificationsRouter);
router.use(threadsRouter);
router.use(dmRouter);
router.use(weatherRouter);
router.use(permitsRouter);
router.use(emergencyContactsRouter);
router.use(gearRouter);
router.use(seasonsRouter);
router.use(teahousesRouter);
router.use(reviewsRouter);
router.use(verificationRouter);
router.use(sosRouter);
router.use(adminRouter);

export default router;
