// @ts-nocheck
import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import treksRouter from "./treks";
import joinRequestsRouter from "./joinRequests";
import customRequestsRouter from "./customRequests";
import bidsRouter from "./bids";
import bookingsRouter from "./bookings";
import dashboardRouter from "./dashboard";
import notificationsRouter from "./notifications";
import threadsRouter from "./threads";
import dmRouter from "./dm";
import weatherRouter from "./weather";
import permitsRouter from "./permits";
import emergencyContactsRouter from "./emergencyContacts";
import gearRouter from "./gear";
import seasonsRouter from "./seasons";
import teahousesRouter from "./teahouses";
import reviewsRouter from "./reviews";
import verificationRouter from "./verification";
import sosRouter from "./sos";
import adminRouter from "./admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(treksRouter);
router.use(joinRequestsRouter);
router.use(customRequestsRouter);
router.use(bidsRouter);
router.use(bookingsRouter);
router.use(dashboardRouter);
router.use(notificationsRouter);
router.use(threadsRouter);
router.use(dmRouter);
router.use(weatherRouter);
router.use(permitsRouter);
router.use(emergencyContactsRouter);
router.use(gearRouter);
router.use(seasonsRouter);
router.use(teahousesRouter);
router.use(reviewsRouter);
router.use(verificationRouter);
router.use(sosRouter);
router.use(adminRouter);

export default router;
